# Generated by Django 6.1.1 on 2026-09-17 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
