# Generated by Django 6.1.1 on 2026-10-02 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresetotp_otp_created_at'),
        ('salons', '0008_salon_established_year_salon_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_phone_verified', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='Male (He/Him)', max_length=50)),
                ('primary_location', models.CharField(blank=True, default='Indiranagar, Bengaluru', max_length=150)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('membership_tier', models.CharField(default='Emerald Member', max_length=50)),
                ('wellness_preferences', models.JSONField(blank=True, default=dict)),
                ('notification_channels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_salons', models.ManyToManyField(blank=True, related_name='favorited_by_customers', to='salons.salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
