# Generated by Django 6.1.1 on 2026-09-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0006_workerprofile_assigned_services_workerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='✂️', help_text='Emoji or icon identifier', max_length=50)),
                ('image', models.TextField(blank=True, default='', help_text='Optional category banner/image URL or base64')),
                ('is_active', models.BooleanField(default=True, help_text='Super Admin can deactivate categories')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order for catalog browsing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('standard_price', models.DecimalField(decimal_places=2, default=500.0, help_text='Suggested platform benchmark price (INR)', max_digits=10)),
                ('standard_duration', models.PositiveIntegerField(default=45, help_text='Suggested standard duration in minutes')),
                ('gender_target', models.CharField(choices=[('ALL', 'Unisex / All'), ('MALE', 'Men'), ('FEMALE', 'Women'), ('KIDS', 'Kids')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Super Admin decides if service is available in platform catalog')),
                ('image', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Standard Service',
                'verbose_name_plural': 'Standard Services',
                'ordering': ['category__display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', help_text="Optional custom branding e.g. 'Signature Botanical Haircut'", max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Salon custom price in INR', max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Salon custom duration in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Salon owner can activate or deactivate this offering')),
                ('description', models.TextField(blank=True, default='', help_text='Salon-specific notes or description for this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='salons.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_offerings', to='services.service')),
            ],
            options={
                'verbose_name': 'Salon Service Offering',
                'verbose_name_plural': 'Salon Service Offerings',
                'ordering': ['service__category__display_order', 'service__name'],
                'unique_together': {('salon', 'service')},
            },
        ),
    ]
