from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView


from .views import (
    AdminUserDetailView,
    AdminUserListView,
    AdminUserToggleBlockView,
    ForgotPasswordRequestView,
    ForgotPasswordResendOTPView,
    ForgotPasswordVerifyOTPView,
    LoginView,
    RegisterView,
    ResendOTPView,
    ResetPasswordConfirmView,
    VerifyOTPView,
    google_success,
)

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "verify-otp/",
        VerifyOTPView.as_view(),
        name="verify_otp",
    ),
    path(
        "resend-otp/",
        ResendOTPView.as_view(),
        name="resend_otp",
    ),
    path(
        "forgot-password/",
        ForgotPasswordRequestView.as_view(),
        name="forgot_password",
    ),
    path(
        "forgot-password/verify-otp/",
        ForgotPasswordVerifyOTPView.as_view(),
        name="forgot_password_verify_otp",
    ),
    path(
        "forgot-password/resend-otp/",
        ForgotPasswordResendOTPView.as_view(),
        name="forgot_password_resend_otp",
    ),
    path(
        "forgot-password/reset/",
        ResetPasswordConfirmView.as_view(),
        name="reset_password_confirm",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "token/refresh/",
        TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path(
        "google-success/",
        google_success,
        name="google_success",
    ),
    path(
        "admin/users/",
        AdminUserListView.as_view(),
        name="admin_user_list",
    ),
    path(
        "admin/users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin_user_detail",
    ),
    path(
        "admin/users/<int:pk>/toggle-block/",
        AdminUserToggleBlockView.as_view(),
        name="admin_user_toggle_block",
    ),
]