from django.urls import path

from .views import (
    AdminDashboardStatsView,
    AdminSalonDetailView,
    AdminSalonListView,
    ApprovedSalonListView,
    CustomerSalonExploreView,
    CustomerSalonDetailView,
    OwnerDashboardView,
    OwnerQuickWalkInView,
    OwnerSalonProfileView,
    OwnerSalonOffDayListView,
    OwnerSalonOffDayDetailView,
    OwnerWorkerDetailView,
    OwnerWorkerListCreateView,
    PendingSalonListView,
    SalonApprovalView,
    SalonCreateView,
    SalonResubmitDataView,
    SalonResubmitView,
    WorkerBookingStatusUpdateView,
    WorkerDashboardView,
)


urlpatterns = [
    path(
        "owner/off-days/",
        OwnerSalonOffDayListView.as_view(),
        name="owner-salon-off-days",
    ),
    path(
        "owner/off-days/<int:pk>/",
        OwnerSalonOffDayDetailView.as_view(),
        name="owner-salon-off-day-detail",
    ),
    path(
        "owner/workers/",
        OwnerWorkerListCreateView.as_view(),
        name="owner-worker-list-create",
    ),
    path(
        "owner/add-worker/",
        OwnerWorkerListCreateView.as_view(),
        name="owner-add-worker",
    ),
    path(
        "owner/workers/<int:pk>/",
        OwnerWorkerDetailView.as_view(),
        name="owner-worker-detail",
    ),
    path(
        "worker/dashboard/",
        WorkerDashboardView.as_view(),
        name="worker-dashboard",
    ),
    path(
        "worker/bookings/<int:pk>/status/",
        WorkerBookingStatusUpdateView.as_view(),
        name="worker-booking-status-update",
    ),
    path(
        "explore/",
        CustomerSalonExploreView.as_view(),
        name="customer-salons-explore",
    ),
    path(
        "owner/dashboard/",
        OwnerDashboardView.as_view(),
        name="owner-dashboard",
    ),
    path(
        "owner/profile/",
        OwnerSalonProfileView.as_view(),
        name="owner-salon-profile",
    ),
    path(
        "owner/walk-in/",
        OwnerQuickWalkInView.as_view(),
        name="owner-quick-walk-in",
    ),
    path(
        "create/",
        SalonCreateView.as_view(),
        name="salon-create",
    ),
    path(
        "<int:pk>/resubmit-data/",
        SalonResubmitDataView.as_view(),
        name="salon-resubmit-data",
    ),
    path(
        "<int:pk>/resubmit/",
        SalonResubmitView.as_view(),
        name="salon-resubmit",
    ),
    path(
        "admin/stats/",
        AdminDashboardStatsView.as_view(),
        name="admin-dashboard-stats",
    ),
    path(
        "admin/salons/",
        AdminSalonListView.as_view(),
        name="admin-salon-list",
    ),
    path(
        "admin/salons/<int:pk>/",
        AdminSalonDetailView.as_view(),
        name="admin-salon-detail",
    ),
    path(
        "admin/<int:pk>/decision/",
        SalonApprovalView.as_view(),
        name="admin-salon-decision",
    ),
    path(
        "pending/",
        PendingSalonListView.as_view(),
        name="pending-salons",
    ),
    path(
        "<int:pk>/approval/",
        SalonApprovalView.as_view(),
        name="salon-approval",
    ),
    path(
        "approved/",
        ApprovedSalonListView.as_view(),
        name="approved-salons",
    ),
    path(
        "<int:pk>/",
        CustomerSalonDetailView.as_view(),
        name="customer-salon-detail",
    ),
    path(
        "",
        ApprovedSalonListView.as_view(),
        name="salon-list",
    ),
]