from django.urls import path

from .views import (
    AdminDashboardStatsView,
    AdminSalonListView,
    ApprovedSalonListView,
    CustomerSalonExploreView,
    OwnerDashboardView,
    OwnerQuickWalkInView,
    PendingSalonListView,
    SalonApprovalView,
    SalonCreateView,
)


urlpatterns = [
    path(
        "explore/",
        CustomerSalonExploreView.as_view(),
        name="customer-salons-explore",
    ),
    path(
        "owner/dashboard/",
        OwnerDashboardView.as_view(),
        name="owner-dashboard",
    ),
    path(
        "owner/walk-in/",
        OwnerQuickWalkInView.as_view(),
        name="owner-quick-walk-in",
    ),
    path(
        "create/",
        SalonCreateView.as_view(),
        name="salon-create",
    ),
    path(
        "admin/stats/",
        AdminDashboardStatsView.as_view(),
        name="admin-dashboard-stats",
    ),
    path(
        "admin/salons/",
        AdminSalonListView.as_view(),
        name="admin-salon-list",
    ),
    path(
        "admin/<int:pk>/decision/",
        SalonApprovalView.as_view(),
        name="admin-salon-decision",
    ),
    path(
        "pending/",
        PendingSalonListView.as_view(),
        name="pending-salons",
    ),
    path(
        "<int:pk>/approval/",
        SalonApprovalView.as_view(),
        name="salon-approval",
    ),
    path(
        "approved/",
        ApprovedSalonListView.as_view(),
        name="approved-salons",
    ),
    path(
        "",
        ApprovedSalonListView.as_view(),
        name="salon-list",
    ),
]