# Generated by Django 6.1.1 on 2026-09-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salon',
            name='category',
            field=models.CharField(blank=True, default='Hair & Styling', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='cover_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='salon',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salon',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='state',
            field=models.CharField(blank=True, default='Karnataka', max_length=100),
        ),
        migrations.AlterField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
