# Generated by Django 6.1.1 on 2026-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_admin_notes_salon_amenities_salon_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
