# Generated by Django 6.1.1 on 2026-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20),
        ),
    ]
