# Generated by Django 6.1.1 on 2026-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_workerprofile_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='assigned_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='commission_tier',
            field=models.CharField(blank=True, default='Tier 2 • Senior Specialist', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='employment_status',
            field=models.CharField(blank=True, default='Full-Time Specialist', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='shift_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='station',
            field=models.CharField(blank=True, default='Chair #01', max_length=100),
        ),
    ]
