# Generated by Django 6.1.1 on 2026-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_workerprofile_assigned_services_workerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='id_card_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_card_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_card_type',
            field=models.CharField(blank=True, default='Aadhaar Card', max_length=50),
        ),
    ]
