# Generated by Django 6.1.1 on 2026-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_workerprofile_id_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='established_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salon',
            name='outlet_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salon',
            name='secondary_category',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salon',
            name='short_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salon',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
