# Generated by Django 6.1.1 on 2026-10-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_salon_established_year_salon_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, default='Scheduled Closure', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='salons.salon')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('salon', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
